version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend7
    ports:
      - "7097:80"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend8
    ports:
      - "3018:3018"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin234
      - DB_NAME=auth_db
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres9
    ports:
      - "5106:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

